= JavaSim Manual Version 2.0

JavaSim is an object-oriented, discrete event simulation toolkit for Java. It's a Java implementation of the original C++SIM simulation toolkit, which was developed as a direct consequence of research conducted within the scope of the Arjuna project from Newcastle University in the 1980's. Therefore, it shares many of the same requirements:

* easy to learn and use: the interface to the simulation library should be easy to understand.
* correct abstraction: existing Java programmers should not find the simulation paradigm in conflict with the programming paradigm presented by Java. Simulation programmers used to other environments should find the transition to JavaSim straightforward.
* flexible and extensible: it should be relatively easy for anyone to add new functionality to the system, such as new distribution functions.
* efficiency: the system should be efficient and produce efficient simulation runs. Simulation packages which we have experience of tended to be extremely slow and consume large amounts of system resources.
